name: "bluebell"
mode: "dev"
start_time: "2020-07-01"
machine_id: 1
port: 8081


auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: mysql8019
  port: 3306
  user: "root"
  password: "12345678"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: redis507
  port: 6379
  #password: "12345678"
  db: 0
  pool_size: 100